### ISSUE TITLE
error: use of undeclared identifier 'safeFreeConst'

### ISSUE THREAD

**Issue by wstclzy2010** [tihmstar/liboffsetfinder64#11]
I can not compile due to the error:
`patchfinder64.cpp:37:19: error: use of undeclared identifier 'safeFreeConst'
    if (_freeBuf) safeFreeConst(_buf);`

**Comment by consllogluke** [comment]
+1 same error here

**Comment by ajsacco** [comment]
Make sure you have the latest libgeneral, as he added support for safeFreeConst

**Comment by tihmstar** [comment]
Try again with version 104
