### ISSUE TITLE
fatal error: mach-o/loader.h: No such file or directory

### ISSUE THREAD

**Issue by TheProgramableTurtle** [tihmstar/liboffsetfinder64#21]
mach-o dependency isn't available on Linux. Perhaps consider a build flag/configuration to exclude the files that use it?

**Comment by tihmstar** [comment]
There is a workaround in https://github.com/tihmstar/liboffsetfinder64/blob/master/.github/workflows/main.yml
To build it for linux

**Comment by mast3rz3ro** [comment]
I'm running into the same issue and trying the workflow build method doesn't helps at all. it's just leads to another errors.

Why just didn't implement a way without needing this library?

I'm using Msys2 with clang 17
