### ISSUE TITLE
vmem::vmem::memstr throws exception instead of returning 0 while finding boot-args string in ibootpatchfinder64::get_boot_arg_patch.

### ISSUE THREAD

**Issue by TheProgramableTurtle** [tihmstar/liboffsetfinder64#22]
If the default boot-args string is not found, vmem::vmem::memstr should return 0 and ibootpatchfinder64::get_boot_arg_patch should fall back to the iOS 13 default string, but instead memstr instead throws an exception
```
terminate called after throwing an instance of 'tihmstar::not_found'
  what():  std::exception
Aborted (core dumped)
```
Temporarily fixed by renaming the DEFAULT_BOOTARGS_STR macro.
Also, how do you get the exceptions to have the full information (like `"memstr failed to find \"%s\""`)?

**Comment by Cryptiiiic** [comment]
this is probably fixed by now

**Comment by tihmstar** [comment]
> this is probably fixed by now

Assuming that's right i'll just close the issue. If the problem persists, please creat a new issue
