### ISSUE TITLE
Error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."

### ISSUE THREAD

**Issue by chr0n1cle** [tihmstar/liboffsetfinder64#3]
config.status: creating Makefile
config.status: creating img4tool/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
configure: WARNING: unrecognized options: --without-cython
~/liboffsetfinder64
configure: WARNING: unrecognized options: --enable-static, --disable-shared, --without-cython, --without-openssl, --without-lzfse
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."

**Comment by sohsatoh** [comment]
clone the repository recursively.
