### ISSUE TITLE
Compiling offsetexporter

### ISSUE THREAD

**Issue by alfiecg24** [tihmstar/liboffsetfinder64#33]
Hi, how do I compile offsetexporter into a binary? If I run `make` inside `tools/` or `tools/offsetexporter/` it says `make[1]: Nothing to be done for 'all-am'.` but there is no compiled binary leftover. Is the binary output at a different path? Thank you!

Edit: building inside Xcode gives me a "'reflected_kernelpatchfinder.cpp' file not found" error inside of `reflected_kernelpatchfinder.cpp`.

**Comment by authorisation** [comment]
Did you end up figuring it out?

**Comment by sanny1** [comment]
Hi just for anyone trying to compile this yes, its related with the makefile, if you uncomment the commented section this error should go away. Its the make file in offsetexporter folder
