### ISSUE TITLE
vsegment.cpp errors

### ISSUE THREAD

**Issue by hc20k** [tihmstar/liboffsetfinder64#5]
After i run autogen.sh and configure and try to make the project, I get these errors
https://pastebin.com/raw/WxsYrvdU

**Comment by 0xfffffff0075e2040** [comment]
same here

**Comment by razmashat** [comment]
same here as well

**Comment by iSn0we** [comment]
I compiled it successfully. This version works with iBoot64Patcher for me.
[liboffsetfinder64.0.dylib.zip](https://github.com/tihmstar/liboffsetfinder64/files/3677589/liboffsetfinder64.0.dylib.zip)

**Comment by NotHereForTheDong** [comment]
Same error

**Comment by 4Benj** [comment]
Yep same

**Comment by Benfxmth** [comment]
I get the same error as well when I try to build it with Xcode.

**Comment by sqlstatement** [comment]
ok we get it vsegment.c is broken just wait until tihmstar fixes it

**Comment by quincs** [comment]
sqlgayment ask joe

**Comment by Cryptiiiic** [comment]
Temporary Compile fix :
cd into liboffsetfinder64 src root
`
cd external/libgeneral
curl "https://cdn.discordapp.com/attachments/453692749653475328/629434710073802752/compile_fix.patch" -o compile_fix.patch
git apply compile_fix.patch`
It should now compile fine.

**Comment by timonline** [comment]
almost but not quite fixed my compile errors:

now i get this:

```
vsegment.cpp: In member function 'tihmstar::offsetfinder64::loc_t tihmstar::offsetfinder64::vsegment::memmem(const void*, size_t)':
vsegment.cpp:40:22: error: '::memmem' has not been declared
     if ((rt = (loc_t)::memmem(_buf, _size, little, little_len))) {
                      ^
```

**Comment by LIY2012** [comment]
I'm trying to compile on a debian system.
Adding #include <string.h> to the top of vsegment.cpp and #include <algorithm> to the top of vmem.cpp got me past those errors.  

Now I'm stuck on: 

In file included from machopatchfinder64.cpp:9:

../include/liboffsetfinder64/machopatchfinder64.hpp:13:10: fatal error: mach-o/loader.h: No such file or directory
 #include <mach-o/loader.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
 
any ideas?

**Comment by onny** [comment]
> I'm trying to compile on a debian system.
> Adding #include <string.h> to the top of vsegment.cpp and #include to the top of vmem.cpp got me past those errors.
> 
> Now I'm stuck on:
> 
> In file included from machopatchfinder64.cpp:9:
> 
> ../include/liboffsetfinder64/machopatchfinder64.hpp:13:10: fatal error: mach-o/loader.h: No such file or directory
> #include <mach-o/loader.h>
> ^~~~~~~~~~~~~~~~~
> compilation terminated.
> 
> any ideas?

Yep having the same issues. Looks like this does not work on Linux systems yet because of this MacOS dependency :(

**Comment by campbellcole** [comment]
I got this working on Linux by simply deleting the kernel and macho cpp and header files and removing them from the makefile because I only needed the iboot patcher

**Comment by tihmstar** [comment]
should be fixed in version 104
