### ISSUE TITLE
Can't find right offsets for ios 13.1.2 on iPhone X

### ISSUE THREAD

**Issue by paranoidnela** [tihmstar/liboffsetfinder64#9]
It finds the wrong offsets leading to wrong patches

**Comment by krisanovdev** [comment]
Same here on iPhone 7 (both iOS 12.1.2 and 13.0)

**Comment by paranoidnela** [comment]
still applies for ios 13.1.3

**Comment by tihmstar** [comment]
Not a useful description of a problem.
Unable to debug/resolv
